/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DcRouteImport } from './routes/dc'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DcDcIdRouteImport } from './routes/dc.$dcId'

const DcRoute = DcRouteImport.update({
  id: '/dc',
  path: '/dc',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DcDcIdRoute = DcDcIdRouteImport.update({
  id: '/$dcId',
  path: '/$dcId',
  getParentRoute: () => DcRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/customers': typeof CustomersRoute
  '/dc': typeof DcRouteWithChildren
  '/dc/$dcId': typeof DcDcIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/customers': typeof CustomersRoute
  '/dc': typeof DcRouteWithChildren
  '/dc/$dcId': typeof DcDcIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/customers': typeof CustomersRoute
  '/dc': typeof DcRouteWithChildren
  '/dc/$dcId': typeof DcDcIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bills' | '/customers' | '/dc' | '/dc/$dcId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bills' | '/customers' | '/dc' | '/dc/$dcId'
  id: '__root__' | '/' | '/bills' | '/customers' | '/dc' | '/dc/$dcId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillsRoute: typeof BillsRoute
  CustomersRoute: typeof CustomersRoute
  DcRoute: typeof DcRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dc': {
      id: '/dc'
      path: '/dc'
      fullPath: '/dc'
      preLoaderRoute: typeof DcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dc/$dcId': {
      id: '/dc/$dcId'
      path: '/$dcId'
      fullPath: '/dc/$dcId'
      preLoaderRoute: typeof DcDcIdRouteImport
      parentRoute: typeof DcRoute
    }
  }
}

interface DcRouteChildren {
  DcDcIdRoute: typeof DcDcIdRoute
}

const DcRouteChildren: DcRouteChildren = {
  DcDcIdRoute: DcDcIdRoute,
}

const DcRouteWithChildren = DcRoute._addFileChildren(DcRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillsRoute: BillsRoute,
  CustomersRoute: CustomersRoute,
  DcRoute: DcRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
