/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRegisterRouteImport } from './routes/app.register'
import { Route as AppDcRouteImport } from './routes/app.dc'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppBillsRouteImport } from './routes/app.bills'
import { Route as AppDcDcIdRouteImport } from './routes/app.dc.$dcId'
import { Route as AppBillsBillIdRouteImport } from './routes/app.bills.$billId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppDcRoute = AppDcRouteImport.update({
  id: '/dc',
  path: '/dc',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppDcDcIdRoute = AppDcDcIdRouteImport.update({
  id: '/$dcId',
  path: '/$dcId',
  getParentRoute: () => AppDcRoute,
} as any)
const AppBillsBillIdRoute = AppBillsBillIdRouteImport.update({
  id: '/$billId',
  path: '/$billId',
  getParentRoute: () => AppBillsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/bills': typeof AppBillsRouteWithChildren
  '/app/customers': typeof AppCustomersRoute
  '/app/dc': typeof AppDcRouteWithChildren
  '/app/register': typeof AppRegisterRoute
  '/app/reports': typeof AppReportsRoute
  '/app/': typeof AppIndexRoute
  '/app/bills/$billId': typeof AppBillsBillIdRoute
  '/app/dc/$dcId': typeof AppDcDcIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/bills': typeof AppBillsRouteWithChildren
  '/app/customers': typeof AppCustomersRoute
  '/app/dc': typeof AppDcRouteWithChildren
  '/app/register': typeof AppRegisterRoute
  '/app/reports': typeof AppReportsRoute
  '/app': typeof AppIndexRoute
  '/app/bills/$billId': typeof AppBillsBillIdRoute
  '/app/dc/$dcId': typeof AppDcDcIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/bills': typeof AppBillsRouteWithChildren
  '/app/customers': typeof AppCustomersRoute
  '/app/dc': typeof AppDcRouteWithChildren
  '/app/register': typeof AppRegisterRoute
  '/app/reports': typeof AppReportsRoute
  '/app/': typeof AppIndexRoute
  '/app/bills/$billId': typeof AppBillsBillIdRoute
  '/app/dc/$dcId': typeof AppDcDcIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/bills'
    | '/app/customers'
    | '/app/dc'
    | '/app/register'
    | '/app/reports'
    | '/app/'
    | '/app/bills/$billId'
    | '/app/dc/$dcId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/bills'
    | '/app/customers'
    | '/app/dc'
    | '/app/register'
    | '/app/reports'
    | '/app'
    | '/app/bills/$billId'
    | '/app/dc/$dcId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/bills'
    | '/app/customers'
    | '/app/dc'
    | '/app/register'
    | '/app/reports'
    | '/app/'
    | '/app/bills/$billId'
    | '/app/dc/$dcId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/register': {
      id: '/app/register'
      path: '/register'
      fullPath: '/app/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dc': {
      id: '/app/dc'
      path: '/dc'
      fullPath: '/app/dc'
      preLoaderRoute: typeof AppDcRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bills': {
      id: '/app/bills'
      path: '/bills'
      fullPath: '/app/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dc/$dcId': {
      id: '/app/dc/$dcId'
      path: '/$dcId'
      fullPath: '/app/dc/$dcId'
      preLoaderRoute: typeof AppDcDcIdRouteImport
      parentRoute: typeof AppDcRoute
    }
    '/app/bills/$billId': {
      id: '/app/bills/$billId'
      path: '/$billId'
      fullPath: '/app/bills/$billId'
      preLoaderRoute: typeof AppBillsBillIdRouteImport
      parentRoute: typeof AppBillsRoute
    }
  }
}

interface AppBillsRouteChildren {
  AppBillsBillIdRoute: typeof AppBillsBillIdRoute
}

const AppBillsRouteChildren: AppBillsRouteChildren = {
  AppBillsBillIdRoute: AppBillsBillIdRoute,
}

const AppBillsRouteWithChildren = AppBillsRoute._addFileChildren(
  AppBillsRouteChildren,
)

interface AppDcRouteChildren {
  AppDcDcIdRoute: typeof AppDcDcIdRoute
}

const AppDcRouteChildren: AppDcRouteChildren = {
  AppDcDcIdRoute: AppDcDcIdRoute,
}

const AppDcRouteWithChildren = AppDcRoute._addFileChildren(AppDcRouteChildren)

interface AppRouteChildren {
  AppBillsRoute: typeof AppBillsRouteWithChildren
  AppCustomersRoute: typeof AppCustomersRoute
  AppDcRoute: typeof AppDcRouteWithChildren
  AppRegisterRoute: typeof AppRegisterRoute
  AppReportsRoute: typeof AppReportsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillsRoute: AppBillsRouteWithChildren,
  AppCustomersRoute: AppCustomersRoute,
  AppDcRoute: AppDcRouteWithChildren,
  AppRegisterRoute: AppRegisterRoute,
  AppReportsRoute: AppReportsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
